accounts/urls.py
from django.contrib import admin
from django.urls import path

from .import views
app_name = "accounts"

urlpatterns = [

    path('login', views.loginpage, name='login'),
    path('register', views.registerpage, name='register'),
    path('logout', views.logoutUser, name='logout'),

]

metropark/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard import views as dashboard
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

from metropark import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', dashboard.homepage),
    # path('form',dashboard.form)
    path('dashboard/', include('dashboard.urls')),
    path('accounts/', include('accounts.urls')),

    # path('dashboard/',include('dashboard.urls')),
    # path('accounts/', include('accounts.urls')),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import  forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django .forms import  ModelForm


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields= ['username','email','password1','password2']

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm

from .forms import CreateUserForm
from django.contrib import messages
from django.contrib.auth import authenticate ,login,logout
from django.contrib.auth.decorators import login_required

def logoutUser(request):
    logout(request)
    return  redirect('accounts:login')


def loginpage(request):
    if request.user.is_authenticated:
        return redirect('dashboard:homepage')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request,username=username,password=password)

            if user is not None:
                login(request,user)
                return redirect('dashboard:details')
            else:
                messages.info(request,"Username Or Password is Incorrect ")


    # return HttpResponse("ddasdasd")
    return render(request, 'accounts/login.html',)

def registerpage(request):
    if request.user.is_authenticated:
        return redirect('dashboard:homepage')
    else:
        form = CreateUserForm()
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request,'Accounts was created for ' + user)

                return redirect('accounts:login')

        context = {'form': form}
# return HttpResponse("Register")
    return render(request, 'accounts/register.html',context)

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>

<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


    <style>
        {#body,#}
        {#html {#}
        {#	margin: 0;#}
        {#	padding: 0;#}
        {#	height: 100%;#}
        {#    background-image: linear-gradient(cornflowerblue, purple);#}
        {#}#}
        {#.user_card {#}
        {#	width: 350px;#}
        {#	margin-top: auto;#}
        {#	margin-bottom: auto;#}
        {#	background: gray;#}
        {#    opacity: 60%;#}
        {#	position: relative;#}
        {#	display: flex;#}
        {#	justify-content: center;#}
        {#	flex-direction: column;#}
        {#	padding: 10px;#}
        {#	box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);#}
        {#	-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);#}
        {#	-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);#}
        {#	border-radius: 40px;#}
        {#height: 200px;#}
        {##}
        {#}#}
        {##}
        {#.form_container {#}
        {#	margin-top: 20px;#}
        {#}#}
        {##}
        {##form-title{#}
        {#	color: #fff;#}
        {##}
        {#}#}
        {##}
        {#.login_btn {#}
        {#	width: 100%;#}
        {#	background: #33ccff !important;#}
        {#	color: white !important;#}
        {#}#}
        {#.login_btn:focus {#}
        {#	box-shadow: none !important;#}
        {#	outline: 0px !important;#}
        {#}#}
        {#.login_container {#}
        {#	padding: 0 2rem;#}
        {#}#}
        {#.input-group-text {#}
        {#	background: #f7ba5b !important;#}
        {#	color: white !important;#}
        {#	border: 0 !important;#}
        {#	border-radius: 0.25rem 0 0 0.25rem !important;#}
        {#}#}
        {#.input_user,#}
        {#.input_pass:focus {#}
        {#	box-shadow: none !important;#}
        {#	outline: 0px !important;#}
        {#}#}

        #messages{

            color: gray;
            {#padding: px;#}
            {#margin-top: px;#}
            text-align: center;
        }body {
             margin: 0;
             padding: 0;
             font-family: sans-serif;
             background: linear-gradient(to right, #b92b27, #1565c0)
         }

        .card {
            margin-bottom: 20px;
            border: none
        }

        .box {
            width: 500px;
            padding: 20px;
            position: absolute;
            {#height: 500px;#}
            top: 50%;
            left: 55%;
            background: #191919;
        ;
            text-align: center;
            transition: 0.25s;
            margin-top: 80px;
                        border-radius: 30px;
            opacity: 80%;
        }

        .box input[type="text"],
        .box input[type="password"] {
            border: 0;
            background: none;
            display: block;
            margin: 20px auto;
            text-align: center;
            border: 2px solid #3498db;
            padding: 10px 10px;
            width: 250px;
            outline: none;
            color: white;
            border-radius: 24px;
            transition: 0.25s
        }

        .box h1 {
            color: white;
            text-transform: uppercase;
            font-weight: 500
        }

        .box input[type="text"]:focus,
        .box input[type="password"]:focus {
            width: 300px;
            border-color: #2ecc71
        }

        .box input[type="submit"] {
            border: 0;
            background: none;
            display: block;
            margin: 20px auto;
            text-align: center;
            border: 2px solid #2ecc71;
            padding: 7px 0px;
            outline: none;
            color: white;
            border-radius: 24px;
            transition: 0.25s;
            cursor: pointer;
            width: 200px;

        }

        .box input[type="submit"]:hover {
            background: #2ecc71
        }

        .forgot {
            text-decoration: underline
        }

    </style>

</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                {#                <form onsubmit="event.preventDefault()" class="box">#}
                <form method="POST" action="" class="box">
                    {% csrf_token %}
                    <h1>Login</h1>
                    <p class="text-muted"> Please enter your login and password!</p>
                    <input type="text" name="username" placeholder="Username">
                    <input type="password" name="password" placeholder="Password">
{#                    <a class="forgot text-muted" href="#">Forgot password?</a>#}
                    <input class="btn login_btn" type="submit" value="Login">
                    {% for messages in messages %}

                        <p id="messages"> {{ messages }}</p>

                    {% endfor %}
                                     <h6 style="color: white">   Don't have an account ? <a href="{% url 'accounts:register' %}" class="ml-2" style="color: white">Sign Up</a>
</h6>
                </form>

                {#                    <div class="col-md-12">#}
                {#                        <ul class="social-network social-circle">#}
                {#                            <li><a href="#" class="icoFacebook" title="Facebook"><i class="fab fa-facebook-f"></i></a></li>#}
                {#                            <li><a href="#" class="icoTwitter" title="Twitter"><i class="fab fa-twitter"></i></a></li>#}
                {#                            <li><a href="#" class="icoGoogle" title="Google +"><i class="fab fa-google-plus"></i></a></li>#}
                {#                        </ul>#}
                {#                    </div>#}


            </div>
        </div>
    </div>
</div>
{#<---------------#}
{#	<div class="container h-100">#}
{#		<div class="d-flex justify-content-center h-100">#}
{#			<div class="user_card">#}
{#				<div class="d-flex justify-content-center">#}
{##}
{##}
{#					<h3 id="form-title">LOGIN</h3>#}
{#				</div>#}
{#				<div class="d-flex justify-content-center form_container">#}
{#					<form method="POST" action="">#}
{#                        {% csrf_token %}#}
{#						<div class="input-group mb-3">#}
{#							<div class="input-group-append">#}
{#								<span class="input-group-text"><i class="fas fa-user"></i></span>#}
{#							</div>#}
{#							<input type="text" name="username" placeholder="Username..." class="form-control">#}
{#						</div>#}
{#						<div class="input-group mb-2">#}
{#							<div class="input-group-append">#}
{#								<span class="input-group-text"><i class="fas fa-key"></i></span>#}
{#							</div>#}
{#								<input type="password" name="password" placeholder="Password..." class="form-control" >#}
{#						</div>#}
{##}
{#							<div class="d-flex justify-content-center mt-3 login_container">#}
{#				 				<input class="btn login_btn" type="submit" value="Login">#}
{#				   			</div>#}
{##}
{#					</form>#}
{#				</div>#}
{##}
{#                {% for messages in messages %}#}
{##}
{#                    <p id="messages"> {{ messages }}</p>#}
{#                {% endfor %}#}
{##}
{#				<div class="mt-1">#}
{#					<div class="d-flex justify-content-center links">#}
{#						Don't have an account? <a href="{% url 'accounts:register' %}" class="ml-2">Sign Up</a>#}
{#					</div>#}
{##}
{#				</div>#}
{#			</div>#}
{#		</div>#}
{#	</div>#}
</body>

</html>

accounts/templates/accounts/register.html
<!DOCTYPE html>
<html>

<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


    <style>
        {#body,#}
        {#html {#}
        {#	margin: 0;#}
        {#	padding: 0;#}
        {#	height: 100%;#}
        {#    background-image: linear-gradient(cornflowerblue, purple);#}
        {#}#}
        {#.user_card {#}
        {#	width: 350px;#}
        {#	margin-top: auto;#}
        {#	margin-bottom: auto;#}
        {#	background: gray;#}
        {#    opacity: 60%;#}
        {#	position: relative;#}
        {#	display: flex;#}
        {#	justify-content: center;#}
        {#	flex-direction: column;#}
        {#	padding: 10px;#}
        {#	box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);#}
        {#	-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);#}
        {#	-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);#}
        {#	border-radius: 40px;#}
        {#height: 200px;#}
        {##}
        {#}#}
        {##}
        {#.form_container {#}
        {#	margin-top: 20px;#}
        {#}#}
        {##}
        {##form-title{#}
        {#	color: #fff;#}
        {##}
        {#}#}
        {##}
        {#.login_btn {#}
        {#	width: 100%;#}
        {#	background: #33ccff !important;#}
        {#	color: white !important;#}
        {#}#}
        {#.login_btn:focus {#}
        {#	box-shadow: none !important;#}
        {#	outline: 0px !important;#}
        {#}#}
        {#.login_container {#}
        {#	padding: 0 2rem;#}
        {#}#}
        {#.input-group-text {#}
        {#	background: #f7ba5b !important;#}
        {#	color: white !important;#}
        {#	border: 0 !important;#}
        {#	border-radius: 0.25rem 0 0 0.25rem !important;#}
        {#}#}
        {#.input_user,#}
        {#.input_pass:focus {#}
        {#	box-shadow: none !important;#}
        {#	outline: 0px !important;#}
        {#}#}

        #messages{

            color: gray;
        {#padding: px;#}
        {#margin-top: px;#}
            text-align: center;
        }body {
             margin: 0;
             padding: 0;
             font-family: sans-serif;
             background: linear-gradient(to right, #b92b27, #1565c0)
         }

        .card {
            margin-bottom: 20px;
            border: none
        }

        .box {
            width: 500px;
            padding: 20px;
            position: absolute;
        {#height: 500px;#}
            top: 20%;
            left: 55%;
            background: #191919;
            opacity: 80%;
        ;
            text-align: center;
            transition: 0.25s;
            margin-top: 80px;
            border-radius: 30px;

        }

        .box input[type="text"],
        .box input[type="password"],
        .box input[type="email"]{
            border: 0;
            background: none;
            display: block;
            margin: 20px auto;
            text-align: center;
            border: 2px solid #3498db;
            padding: 10px 10px;
            width: 250px;
            outline: none;
            color: white;
            border-radius: 24px;
            transition: 0.25s
        }

        .box h2 {
            color: white;
            text-transform: uppercase;
            font-weight: 500
        }

        .box input[type="text"]:focus,
        .box input[type="email"]:focus,
        .box input[type="password"]:focus {
            width: 300px;
            border-color: #2ecc71
        }

        .box input[type="submit"] {
            border: 0;
            background: none;
            display: block;
            margin: 20px auto;
            text-align: center;
            border: 2px solid #2ecc71;
            padding: 0px 0px;
            outline: none;
            color: white;
            border-radius: 24px;
            transition: 0.25s;
            cursor: pointer;
            width: 200px;

        }

        .box input[type="submit"]:hover {
            background: #2ecc71
        }

        .forgot {
            text-decoration: underline
        }

    </style>

</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                {#                <form onsubmit="event.preventDefault()" class="box">#}
                <form method="POST" action="" class="box">
                    {% csrf_token %}
                    <h2>REGISTER ACCOUNT</h2>
                    {#                    <p class="text-muted"> Please enter your login and password!</p>#}
                    {{ form.username }}
                    {{ form.email }}
                    {{ form.password1 }}
                    {{ form.password2 }}

                    {#<a class="forgot text-muted" href="#">Forgot password?</a>#}
                    <input class="btn login_btn" type="submit" value="Login">
                    <div style="color: white;text-align: center;margin-right: 0px">
                        {% for field, error in form.errors.items %}
                            <div class="  my- p-" role="alert">
                                {{ error|striptags }}
                            </div>
                        {% endfor %}
                    </div>
                    <h6 style="color: white;margin-top:10px">
                        Already have an account ?
                        <a href="{% url 'accounts:login' %}" class="ml-2" style="color: white">Login</a>
                    </h6>
                </form>

                {#                    <div class="col-md-12">#}
                {#                        <ul class="social-network social-circle">#}
                {#                            <li><a href="#" class="icoFacebook" title="Facebook"><i class="fab fa-facebook-f"></i></a></li>#}
                {#                            <li><a href="#" class="icoTwitter" title="Twitter"><i class="fab fa-twitter"></i></a></li>#}
                {#                            <li><a href="#" class="icoGoogle" title="Google +"><i class="fab fa-google-plus"></i></a></li>#}
                {#                        </ul>#}
                {#                    </div>#}


            </div>
        </div>
    </div>
</div>
<script>

    //Query All input fields
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder='Username..';
    form_fields[2].placeholder='Email..';
    form_fields[3].placeholder='Enter password...';
    form_fields[4].placeholder='Re-enter Password...';


    for (var field in form_fields){
        form_fields[field].className += ' form-control'
    }
</script>
{#<---------------#}
{#	<div class="container h-100">#}
{#		<div class="d-flex justify-content-center h-100">#}
{#			<div class="user_card">#}
{#				<div class="d-flex justify-content-center">#}
{##}
{##}
{#					<h3 id="form-title">LOGIN</h3>#}
{#				</div>#}
{#				<div class="d-flex justify-content-center form_container">#}
{#					<form method="POST" action="">#}
{#                        {% csrf_token %}#}
{#						<div class="input-group mb-3">#}
{#							<div class="input-group-append">#}
{#								<span class="input-group-text"><i class="fas fa-user"></i></span>#}
{#							</div>#}
{#							<input type="text" name="username" placeholder="Username..." class="form-control">#}
{#						</div>#}
{#						<div class="input-group mb-2">#}
{#							<div class="input-group-append">#}
{#								<span class="input-group-text"><i class="fas fa-key"></i></span>#}
{#							</div>#}
{#								<input type="password" name="password" placeholder="Password..." class="form-control" >#}
{#						</div>#}
{##}
{#							<div class="d-flex justify-content-center mt-3 login_container">#}
{#				 				<input class="btn login_btn" type="submit" value="Login">#}
{#				   			</div>#}
{##}
{#					</form>#}
{#				</div>#}
{##}
{#                {% for messages in messages %}#}
{##}
{#                    <p id="messages"> {{ messages }}</p>#}
{#                {% endfor %}#}
{##}
{#				<div class="mt-1">#}
{#					<div class="d-flex justify-content-center links">#}
{#						Don't have an account? <a href="{% url 'accounts:register' %}" class="ml-2">Sign Up</a>#}
{#					</div>#}
{##}
{#				</div>#}
{#			</div>#}
{#		</div>#}
{#	</div>#}
</body>

</html>
{#<!DOCTYPE html>#}
{#<html>#}
{##}
{#<head>#}
{#	<title>Login</title>#}
{#	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">#}
{#	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>#}
{#	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">#}
{##}
{#	<style>#}
{#		body,#}
{#		html {#}
{#			margin: 0;#}
{#			padding: 0;#}
{#			height: 100%;#}
{#			background: #7abecc !important;#}
{#		}#}
{#		.user_card {#}
{#			width: 350px;#}
{#			margin-top: auto;#}
{#			margin-bottom: auto;#}
{#			background: #74cfbf;#}
{#			position: relative;#}
{#			display: flex;#}
{#			justify-content: center;#}
{#			flex-direction: column;#}
{#			padding: 10px;#}
{#			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);#}
{#			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);#}
{#			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);#}
{#			border-radius: 30px;#}
{##}
{#		}#}
{##}
{#		.form_container {#}
{#			margin-top: 20px;#}
{#		}#}
{##}
{#		#form-title{#}
{#			color: #fff;#}
{#		}#}
{#		.login_btn {#}
{#			width: 100%;#}
{#			background: #33ccff !important;#}
{#			color: white !important;#}
{#		}#}
{#		.login_btn:focus {#}
{#			box-shadow: none !important;#}
{#			outline: 0px !important;#}
{#		}#}
{#		.login_container {#}
{#			padding: 0 2rem;#}
{#		}#}
{#		.input-group-text {#}
{#			background: #f7ba5b !important;#}
{#			color: white !important;#}
{#			border: 0 !important;#}
{#			border-radius: 0.25rem 0 0 0.25rem !important;#}
{#		}#}
{#		.input_user,#}
{#		.input_pass:focus {#}
{#			box-shadow: none !important;#}
{#			outline: 0px !important;#}
{#		}#}
{##}
{#	</style>#}
{##}
{#</head>#}
{#<body>#}
{#	<div class="container h-100">#}
{#		<div class="d-flex justify-content-center h-100">#}
{#			<div class="user_card">#}
{#				<div class="d-flex justify-content-center">#}
{#					<h3 id="form-title">REGISTER ACCOUNT</h3>#}
{#				</div>#}
{#				<div class="d-flex justify-content-center form_container">#}
{##}
{#					<form method="POST" action="">#}
{#                        {% csrf_token %}#}
{#						<div class="input-group mb-2">#}
{#							<div class="input-group-append">#}
{#								<span class="input-group-text"><i class="fas fa-user"></i></span>#}
{#							</div>#}
{#							{{ form.username }}#}
{#                            <input type="text" name="username">#}
{#						</div>#}
{#						<div class="input-group mb-2">#}
{#							<div class="input-group-append">#}
{#								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>#}
{#							</div>#}
{#							{{ form.email }}#}
{#                            <input type="email" name="email">#}
{#						</div>#}
{#						<div class="input-group mb-2">#}
{#							<div class="input-group-append">#}
{#								<span class="input-group-text"><i class="fas fa-key"></i></span>#}
{#							</div>#}
{#                            {{ form.password1 }}#}
{#							<input type="text" name="password1">#}
{#						</div>#}
{#						<div class="input-group mb-2">#}
{#							<div class="input-group-append">#}
{#								<span class="input-group-text"><i class="fas fa-key"></i></span>#}
{#							</div>#}
{#                            {{ form.password2 }}#}
{#							<input type="text" name="password2">#}
{#						</div>#}
{##}
{#				   		<div class="d-flex justify-content-center mt-3 login_container">#}
{#				 			<input class="btn login_btn" type="submit" value="Register Account">#}
{#				   		</div>#}
{#					</form>#}
{#				</div>#}
{#                {{ form.errors }}#}
{##}
{#				<div class="mt-4">#}
{#					<div class="d-flex justify-content-center links">#}
{#						Already have an account? <a href="{% url 'accounts:login' %}" class="ml-2">Login</a>#}
{#					</div>#}
{#				</div>#}
{#			</div>#}
{#		</div>#}
{#	</div>#}
{#	<script>#}
{#						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript#}
{#		//We start indexing at one because CSRF_token is considered and input field#}
{#		 */#}
{##}
{#		//Query All input fields#}
{#		var form_fields = document.getElementsByTagName('input')#}
{#		form_fields[1].placeholder='Username..';#}
{#		form_fields[2].placeholder='Email..';#}
{#		form_fields[3].placeholder='Enter password...';#}
{#		form_fields[4].placeholder='Re-enter Password...';#}
{##}
{##}
{#		for (var field in form_fields){#}
{#			form_fields[field].className += ' form-control'#}
{#		}#}
{#	</script>#}
{#</body>#}
{#</html>#}
{##}
{##}