accounts/urls.py
from django.contrib import admin
from django.urls import path

from .import views
app_name = "accounts"

urlpatterns = [

    path('login', views.loginpage, name='login'),
    path('register', views.registerpage, name='register'),
    path('logout', views.logoutUser, name='logout'),

]

dashboard/urls.py
from django.contrib import admin
from django.urls import path

from .import views
app_name = "dashboard"

urlpatterns = [
    path('', views.homepage, name='homepage'),

    path('form/', views.booking, name='booking'),
    path('details/', views.details, name='details'),
    # path('bk_form/', views.bk_form, name='bk_form'),

]

metropark/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard import views as dashboard
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

from metropark import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', dashboard.homepage),
    # path('form',dashboard.form)
    path('dashboard/', include('dashboard.urls')),
    path('accounts/', include('accounts.urls')),

    # path('dashboard/',include('dashboard.urls')),
    # path('accounts/', include('accounts.urls')),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

class Temp(models.Model):
    search_name = models.TextField(blank=True, max_length="10000")
    from_date_tem = models.TextField(blank=True, max_length="10000")


    def __str__(self):
        return f"{self.search_name} + {self.from_date_tem} "

# Create your models here.
class customer(models.Model):
    customer_name = models.TextField(blank=True, max_length="200")
    customer_id = models.TextField(blank=True, max_length="50")
    customer_phone = models.TextField(blank=True,max_length="50")
    customer_email = models.TextField(blank=True,max_length="50")
    vehicle_number = models.TextField(blank=True, max_length="50")
    vehicle_name = models.TextField(blank=True,max_length="50")
    vehicle_color = models.TextField(blank=True,max_length="50")
    vehicle_documents = models.ImageField(blank=False, null=False, default='default.png')

    # vehicle_documents =  models.FileField(upload_to='documents/%Y/%m/%d')


    def __str__(self):
        return f"{self.customer_name}  "


class Key_table(models.Model):
    key_name = models.TextField(blank=True, max_length='100')

    def __str__(self):
        return f"{self.key_name}"

class Slot_duration_table(models.Model):
    from_date = models.TextField(blank=True, max_length='100')
    to_date = models.TextField(blank=True, max_length='100')

    def __str__(self):
        return f"{self.from_date} + {self.to_date}"



class slots_booking_table(models.Model):
    # slot_name = models.TextField(blank=True, max_length='100')
    Slot_duration = models.ForeignKey(Slot_duration_table, blank=True,on_delete=models.CASCADE)
    customer_info = models.ForeignKey(customer, blank=True,on_delete = models.CASCADE)
    total_price =  models.TextField(blank=True, max_length='100')


    def __str__(self):
        return f" {self.Slot_duration} + {self.customer_info}"


class parking_spaces(models.Model):
    spcae_pic = models.ImageField(blank=False, null=False, default='default.png')
    space_name = models.TextField(blank=True, max_length="100")
    space_address = models.TextField(blank=True, max_length="1000")
    total_slots = models.IntegerField(blank=True)
    key_words = models.ManyToManyField(Key_table, blank=True)
    slot_booking = models.ManyToManyField(slots_booking_table, blank=True)
    # slot_monthly_rates = models.IntegerField(blank=True)
    slot_rates = models.IntegerField(blank=True)

    def __str__(self):
        return f"{self.space_name}"

dashboard/forms.py
from django import forms
from . import models






class Customer_details(forms.ModelForm):
    class Meta:
        model = models.customer
        fields = ['customer_name', 'customer_id', 'customer_phone', 'customer_email', 'vehicle_number', 'vehicle_name',
                  'vehicle_color','vehicle_documents']



    def __init__(self, *args, **kwargs):
        super(Customer_details, self).__init__(*args, **kwargs)
        self.fields['customer_name'].widget.attrs['placeholder'] = 'Full Name'
        self.fields['customer_id'].widget.attrs['placeholder'] = 'Identity Number'
        self.fields['customer_phone'].widget.attrs['placeholder'] = 'Phone Number'
        self.fields['customer_email'].widget.attrs['placeholder'] = 'Email Address @gmail.com'
        self.fields['vehicle_number'].widget.attrs['placeholder'] = 'GF 20 WSN'
        self.fields['vehicle_name'].widget.attrs['placeholder'] = 'e.g. Ford 2005'
        self.fields['vehicle_color'].widget.attrs['placeholder'] = 'White,Blue,Black .....'

        # self.fields['customer_name'].widget.attrs['required'] = 'required'
        # self.fields['customer_id'].widget.attrs['required'] = 'required'
        # self.fields['customer_phone'].widget.attrs['required'] = 'required'
        # self.fields['customer_email'].widget.attrs['required'] = 'required'
        # self.fields['vehicle_number'].widget.attrs['required'] = 'required'
        # self.fields['vehicle_name'].widget.attrs['required'] = 'required'
        # self.fields['vehicle_color'].widget.attrs['required'] = 'required'

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = ' form-control'
            visible.field.widget.attrs['style'] = 'height: 34px; width: 555px; resize:none'
            visible.field.widget.attrs['resize'] = 'none'
            # visible.field.widget.attrs['max'] = '1'
            # visible.field.widget.attrs['min'] = '0'


class slots_booking(forms.ModelForm):
    class Meta:
        model = models.slots_booking_table
        fields = ['Slot_duration','customer_info','total_price']


    def __init__(self, *args, **kwargs):
        super(slots_booking, self).__init__(*args, **kwargs)
        # self.fields['slot_name'].widget.attrs['placeholder'] = 'slot_name'
        self.fields['Slot_duration'].widget.attrs['placeholder'] = 'Slot_duration'


        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = ' form-control,'
            visible.field.widget.attrs['style'] = 'height: 34px; width: 555px; resize:none'
            visible.field.widget.attrs['resize'] = 'none'

            # visible.field.widget.attrs['max'] = '1'
            # visible.field.widget.attrs['min'] = '0'

class parking_spaces_form(forms.ModelForm):
    class Meta:
        model = models.parking_spaces
        fields = ['slot_booking']


# class slot_duration_table_form(forms.ModelForm):
#     class Meta:
#         model = models.Slot_duration_table
#         fields = ['Slot_duration_table']

dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from datetime import datetime

from . import forms

# Create your views here.
from .forms import Customer_details
from .models import parking_spaces, slots_booking_table, Temp, Slot_duration_table


# @login_required(login_required, name='dispatch')
# @login_required(login_url='/accounts/login')
# def booking(request):
#     parking_space1 = parking_spaces.objects.get(space_name='Link Road')
#     slb = slots_booking_table.objects.all()
#
#     if request.method == 'POST':
#
#         print("method is post")
#         form = forms.Customer_details(request.POST, request.FILES)
#
#         if form.is_valid():
#             # instance = form.save(commit=False)
#             print("inside form is valid")
#             form.save()
#
#             # # parking_space.slot_booking.add(form)
#             # abc = slots_booking_table.customer_info.add(form)
#             # parking_space1.slot_booking.add(abc)
#             # # @login_required(login_url='/accounts/login')
#             # return details(request)
#             return details(request)
#             # return HttpResponse("hjk")
#
#     form = forms.Customer_details()
#     print("inside Else")
#
#     return render(request, 'dashboard/search_form.html', {'form': form})
#
#
# @login_required(login_url='/accounts/login')
# def details(request):
#     return render(request, 'dashboard/details.html')
#
#
# def bk_form(request, location, duration, from_date):
#     sp = parking_spaces.objects.filter(space_name=location)
#
#     # x = datetime.datetime(2018, 6, 1)
#     # print(x)
#     # slout_bk = slots_booking_table.objects.all()
#     print(location)
#     print(from_date)
#     if request.method == 'POST':
#         form = forms.Customer_details()
#         if form.is_valid():
#             # instance = form.save(commit=False)
#             print("inside form is valid")
#             form.save()
#
#             # parking_space.slot_booking.add(form)
#             # abc = slots_booking_table.customer_info.add(form)
#             # sp.slot_booking.add(abc)
#         # abc = slout_bk.customer_info.save(form)
#         # sp.slot_booking.add(abc)
#         # print(duration, from_date)
#
#         return render(request, 'dashboard/search_form.html', {'form': form, 'sp': sp})
#     return HttpResponse("ghjk")
#
#
# # @login_required(login_url='/accounts/login')
# def homepage(request):
#     live = parking_spaces.objects.all()
#     duration = request.POST.get('options-outlined')
#
#     print(duration)
#     location = request.POST.get('location_address')
#     date = request.POST.get('date')
#     print(location)
#
#     if request.method == 'POST':
#         return bk_form(request, location, duration, date)
#
#     #     sp = parking_spaces.objects.all()
#     #
#     #
#     #
#     #
#     #     sp = parking_spaces.objects.filter(space_name=location)
#     #
#     #
#     #     print("inside Else22")
#     #     request.method = 'GET'
#     #     return render(request, 'dashboard/search_form.html', {'form': form,'sp':sp})
#     return render(request, 'dashboard/homepage.html', {'live': live})

def booking(request):
    live = parking_spaces.objects.all()
    # parking_space1  = parking_spaces.objects.get(space_name='Link Road')


    if request.method == 'POST':

    #     print("method is post")
        form = forms.Customer_details(request.POST,request.FILES)
        form1 = forms.slots_booking(request.POST, None)
        form2 = forms.parking_spaces_form(request.POST, None)



        if form.is_valid() and form1.is_valid():
            # instance = form.save(commit=False)
            print("inside form is valid")



            ss = Temp.objects.get()
            print('ss',ss )


            print('----------------------')

            # nms = Temp.objects.values_list('search_name', flat=True)
            # a = parking_spaces.objects.filter(space_name__in=nms)
            #
            #
            # from_date = Temp.objects.values_list('from_date_tem', flat=True)
            # to_date = request.POST.get('to_date')




            # format = '%Y-%m-%dT%H:%M'  # The format
            # from_date_str = datetime.strptime(from_date, format)
            # print(from_date)
            # print(to_date)
            # print(from_date_str)


            #

            #
            # print(to_date)

            # parking_spaces.slot_booking(a)
            # parking_spaces.save()

            # if a is True:
            #     print("YEs")
            #
            # if a is False:
            #     print("No")
            #
            # print(a[0])

            #
            # for l in live:
            #
            #     a =
            #     print(a[0])

            from_date = request.session['from_date1']
            to_date = request.session['to_date1']
            hours = request.session['hourspass']

            print(from_date)
            print(to_date)
            print('Total',hours)





            #
            #     name = l.space_name
            #     print(name)
            #     if l.space_name == ss:
            #         print("ok")
            #     else:
            #         print("Not Okay")
            print('----------------------')

            dur = Slot_duration_table(to_date=to_date, from_date=from_date)
            dur.save()

            form  = form.save()
            ms = form1.save(commit=False)
            ms.customer_info = form
            ms.Slot_duration = dur

            # parking_spaces.slot_booking.add[1](ms)
            # ms.save()

            ok1 = request.session['location_address1']
            print(ok1)



            # results = Model.objects.filter(x=5).exclude(a=true)

            # check = parking_spaces.objects.filter(space_name=ok1).exclude(a=ok1)
            # print(check)
            # ob = parking_spaces(space_name=ok1)
            ob = parking_spaces.objects.get(space_name=ok1)

            toobb =  ob.total_slots
            print('toobb',toobb)



            rt = ob.slot_rates
            Total_Hr =  rt * hours
            # tsr = slots_booking_table(total_price=Total_Hr)
            ms.total_price = Total_Hr
            print(Total_Hr)

            request.session['Total_Price'] = Total_Hr



            # ob .save()
            ms.save()
            ob.slot_booking.add(ms)
            ob.save()

            print(ob)




            # form1.save_m2m =
            # for live in live:
            #
            #     parking_spaces.space_name.a = form1
                    # live.space_name = form1

            # parking_spaces.slot_booking = ms


            # ms = live.model.slot_booking

            # my_obj.categories.create(name='val1')
            # ms2.slot_booking = form1.save()


            # slot = form1.save(commit=False)
            #
            # cus.id = slot.action_id
            #
            # cus.save()
            # slot.save()
            # form.user = request.user
            # form.save()
            # obj.education.add(edu)
            # form1.save()

            # ab = slots_booking_table.customer_info.add(form1)
            # ab.save()
            # form1.user = request.user
            # slb = slots_booking_table.objects.count()
            Remeaning = toobb - 1
            # ps = parking_spaces.total_slots.co
            # print(ps)
            print('Total Objects', Remeaning)
            ob.total_slots = Remeaning
            ob.save()
            # hg =parking_spaces.objects.filter(space_name=ok1)
            # hg.save()

            # parking_space.slot_booking.add(form)
            # abc = slots_booking_table.customer_info.add(form)
            # parking_space1.slot_booking.add(abc)
            # @login_required(login_url='/accounts/login')
            # return details(request)
            return details(request)
            # return HttpResponse("hjk")

    form = forms.Customer_details()
    print("inside Else")


    return render(request, 'dashboard/search_form.html', {'form': form,'form1': form1,'live': live})

@login_required(login_url='/accounts/login')
def details(request):
    return render(request, 'dashboard/details.html')

# @login_required(login_url='/accounts/login')
def homepage(request):

    live = parking_spaces.objects.all()


    if request.method == 'POST':

        sp = parking_spaces.objects.all()
        ss = slots_booking_table.objects.all()



        slot_dur = Slot_duration_table.objects.filter()

        Temp1 = Temp.objects.all()


        # print(Temp1)
        # duration = request.POST.get('options-outlined')
        # print(duration)



        # Temp.search_name.clear()


        location = request.POST.get('location_address')
        request.session['location_address1'] = location
        print(location)

        from_date = request.POST.get('from_date')
        to_date = request.POST.get('to_date')

        request.session['from_date1'] = from_date
        request.session['to_date1'] = to_date

        from_date1 = request.POST.get('from_date')
        from_date1 = datetime.strptime(from_date1, '%Y-%m-%dT%H:%M')
        print(from_date1)

        to_date1 = request.POST.get('to_date')
        to_date1 = datetime.strptime(to_date1, '%Y-%m-%dT%H:%M')
        print(to_date1)

        diff = to_date1 - from_date1
        print("Diff : ", diff)
        sec = diff.total_seconds()
        hours = sec / 3600
        print("Hours", hours)
        # Hrro = round(hours, 2)
        # print(Hrro)
        request.session['hourspass'] = hours

        Temp1.delete()
        search = Temp(search_name=location)
        search.save()



        # from_date = datetime.strptime(from_date, '%Y-%m-%dT%H:%M')
        # print(from_date)
        # #
        # to_date = request.POST.get('to_date')
        # to_date = datetime.strptime(to_date, '%Y-%m-%dT%H:%M')

dashboard/templates/dashboard/details.html
{% extends 'base_template.html' %}
{% load static %}

{% block header %}


    {% endblock %}

{% block content %}
<h1 style="text-align: center;"> Your Slot is Booked </h1>

{% endblock %}

dashboard/templates/dashboard/homepage.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>asdasd</title>#}
{#</head>#}
{#<body>#}
{#asasd#}
{#</body>#}
{#</html>#}

{% extends 'base_template.html' %}
{% load static %}

{% block header %}


    {% endblock %}

{% block content %}
<div class="container-fluid" >

    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" style="background-color: black">
        <ol class="carousel-indicators">
            <li style="background-color: gray" data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li  style="background-color: gray"data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li style="background-color: gray" data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            <li  style="background-color: gray"data-target="#carouselExampleIndicators" data-slide-to="2"></li>

        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'images/1.png' %}" width="100%" height="470px" alt="First slide">
                <div class="carousel-caption d-none d-md-block">
                    <h5></h5>
                    <p></p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/2.png' %}" width="100%" height="470px" alt="Second slide">

                {#            <img class="d-block w-100" src="https://placeimg.com/1080/500/arch" alt="Second slide" width="10%">#}
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/3.png' %}" width="100%" height="470px" alt="Third slide">

                {#            <img class="d-block w-100" src="https://placeimg.com/1080/500/nature" alt="Third slide">#}
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/4.png' %}" width="100%" height="470px" alt="Fouth slide">

                {#            <img class="d-block w-100" src="https://placeimg.com/1080/500/arch" alt="Second slide" width="10%">#}
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <i class="fas fa-chevron-circle-left fa-2x" ></i>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <i class="fas fa-chevron-circle-right fa-2x" style="color: grey;"></i>
            <span class="sr-only" >Next</span>
        </a>
    </div>
</div>


{% endblock %}

dashboard/templates/dashboard/search_form.html
{% extends 'base_template.html' %}
{% load static %}


{% block content %}
    <form id="theForm2" class="form-group " method="POST" action="{% url 'dashboard:booking' %}" enctype="multipart/form-data">
        {#            <form id="theForm2" class="form-group " action="{% url 'dashboard:resumeform2' %} " method="post" enctype="multipart/form-data">#}

        {% csrf_token %}
        <div class="container">


            <h2 style="text-align: center">Complete Booking </h2>
            <div class="row">

                {% for sp in sp %}
                    <div class="col-6">
                        <h4 style="text-align: center">Parking Space  Picture</h4>
                        <img  style="width: 100%; height: 300px" src="{{ sp.spcae_pic.url }}">
                    </div>
                    <div class="col-6">
                        <h4 style="text-align: center;margin-bottom: 20px">Parking Space  Details</h4>
                        <label style="font-size: 15px;margin-bottom: 10px">Space Parking Name : </label>{{ sp.space_name }}<br>
                        <label style="font-size: 15px;margin-bottom: 10px"> Space Address : </label>{{ sp.space_address }}<br>
                        <label style="font-size: 15px;margin-bottom: 10px">Total Slots : </label>{{ sp.total_slots }}<br>
                        {#                     <label style="font-size: 15px">Space Parking Name : </label>{{ sp.key_words }}<br>#}
                        <label style="font-size: 15px;margin-bottom: 10px">Slot Rates : </label>{{ sp.slot_rates }} $<br>



                    </div>
                {% endfor %}
            </div>

            <div class="row" style="margin-top: 30px ">
                <div class="col-6">
                    <h4 style="text-align: center;">Customer Details</h4>

                    <label>Name:</label>
                    {#                    <input type="text" class="form-control" placeholder="Full Name" name="cust_name">#}
                    {{ form.customer_name }}
                    <br>

                    <label>Id Card n.o:</label>
                    {#                  <input type="text" class="form-control" placeholder="Identity Number" name="cust_id_no">#}
                    {{ form.customer_id }}
                    <br>
                    <label>Phone:</label>
                    {#                    <input type="text" class="form-control" placeholder="Phone Number" name="cust_phone">#}
                    {{ form.customer_phone }}
                    <br>

                    <label>Email:</label>
                    {#                   <input type="text" class="form-control" placeholder="Email Address @gmail.com" name="cust_mail">#}
                    {{ form.customer_email }}
                </div>

                <div class="col-6">
                    <h4 style="text-align: center;">Vehicle Details</h4>

                    <label> Vehicle Name and Model :</label>
                    {#                  <input type="text" class="form-control" placeholder="e.g. Ford 2005" name="vehicle_name">#}
                    {{ form.vehicle_number }}
                    <br>

                    <label>Vehicle Number Plate:</label>
                    {#                  <input type="text" class="form-control" placeholder="GF 20 WSN" name="vehicle_number_plate">#}
                    {{ form.vehicle_name }}
                    <br>

                    <label>Vehicle Color:</label>
                    {#                  <input type="text" class="form-control" placeholder="White,Blue,Black ....." name="vehicle_color">#}
                    {{ form.vehicle_color }}
                    <br>

                    <label>Vehicle Documents:</label>
                    {#                    <input type="file" class="form-control"  name="vehicle_documents">#}
                    {{ form.vehicle_documents }}





                    {#   {% for for in form1 %}#}
                    {##}



                    {#                    {{ form1.customer_info }}#}

                    {#   {% endfor %}#}


                </div>
            </div>
            <br>


            <div class="row">

                <h4 style="text-align: center;">Slot Booking</h4>

                <div class="col-6">
                    {#                    <label>Slot Name :</label>#}
                    {##}
                    {#                  <input type="text" class="form-control" placeholder="White,Blue,Black ....." name="vehicle_color">#}
                    {#                    {{ form1.slot_name }}#}
                    <br>


                    {% for sp in sp %}
                        <label>Total Rates: </label><br><b> ( Hours) * (Slot Rate) :</b>
                        ({{ hours }}) x ({{ sp.slot_rates }})  = {% widthratio sp.slot_rates 1 hours %} $

                    {% endfor %}
                    {#                    {{ form1.Slot_duration }}#}

                    {#                    <div class="row">#}
                    {#                        <div class="col-1">#}
                    {#                            <input type='text' class="form-control " placeholder="TO" disabled style="width: 45px">#}
                    {#                        </div>#}
                    {#                        <div class="col-4" style="margin-top: 7px;">#}
                    {#                            {% for sd in Temp1 %}#}
                    {#                                {% if forloop.last %}#}
                    {#                                {{ sd.from_date_tem }}#}
                    {#                                {% endif %}#}
                    {#                            {% endfor %}#}
                    {#                        </div>#}

                    {#                        <div class="col-2">#}
                    {#                            <input type='text' class="form-control " placeholder="From" disabled style="width: 60px; ">#}
                    {#                        </div>#}
                    {#                        <div class="col-5">#}
                    {#                            <input class="form-control" type="datetime-local" id="to_date" name="to_date" >#}
                    {#                        </div>#}
                    {#                    </div>#}


                </div>
                <div class="col-6"><br>
                    {#                     <h4 style="text-align: center;">Slot Booking</h4>#}
                    <label>Slot Duration :</label><br>
                    <p><b>From Date : </b> {{ from_date1 }}</p>

                    {#                  <input type="text" class="form-control" placeholder="White,Blue,Black ....." name="vehicle_color">#}

                    <p><b>To Date   : </b> {{ to_date1 }}</p>




                    {#                  <input type="text" class="form-control" placeholder="White,Blue,Black ....." name="vehicle_color">#}
                </div>

            </div>
            <br>
            <div style="text-align: center;"> <button type="submit" class="btn btn-secondary" style="width: 20%">Book With Out Paypal Payment</button></div>
            {#Paypal#} <br>
              <div style="text-align: center;">   <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModal">Paypal Payment</button>

              </div>
        </div>
    </form>
    {#   <script src="https://www.paypal.com/sdk/js?client-id=test&currency=USD"></script>#}
    <script src="https://www.paypal.com/sdk/js?client-id=ATdoVzsapMZ3o3PTczgMdoweKfOs27xv1gLRnbwlBcdlMBWGC6fDSRujUdtlNPm6NlEGIZ6Or7kpdIOQ&currency=USD"></script>


    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document" style="left: -1%;transform: translate(0,0%)">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="exampleModalLabel" style="margin-left:120px ">PayPal Payment Gateway</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                    <div id="paypal-button-container"></div>
                    {#&disable-funding=credit#}

                    <script>

                        {% for sp  in sp %}
                            var sr =   {{ sp.slot_rates }}
                            var hr =  {{ hours }}
                            {#alert(sr)#}
                            {#alert(hr)#}

                            TotalHR = sr * hr
                            {#alert(TotalHR)#}
                        {% endfor %}

                        {#var  a =   '{{ hours }}'#}
                        {#var v = '{{ sp.slot_rates }}'#}
                        {#c = a * v#}
                        {#alert(c)#}
                        // Render the PayPal button into #paypal-button-container

                        {#alert(total)#}
                        {##}



                        paypal.Buttons({

                            style: {
                                color:  'blue',
                                shape:  'pill',
                                label:  'pay',
                                height: 40,
                            },
                            // Set up the transaction
                            createOrder: function(data, actions) {
                                return actions.order.create({
                                    purchase_units: [{
                                        amount: {
                                            value: TotalHR
                                        }
                                    }]
                                });
                            },

                            // Finalize the transaction
                            onApprove: function(data, actions) {
                                return actions.order.capture().then(function(details) {
                                    // Show a success message to the buyer
                                    alert('Transaction completed by ' + details.payer.name.given_name + '!');
                                    document.getElementById('theForm2').submit();
                                });
                            }


                        }).render('#paypal-button-container');
                    </script>
                </div>

                {#                        <div class="modal-footer">#}
                {#                            <input class="  btn btn-primary" type="submit" value="create">#}
                {#                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>#}
                {#                        </div>#}
            </div>
        </div>
    </div>




{% endblock %}